# Generated by Django 3.0.5 on 2020-04-28 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='艺人',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('头像', models.ImageField(upload_to='touxiang/')),
                ('名字', models.CharField(max_length=10, unique=True)),
                ('性别', models.CharField(max_length=5)),
                ('出生', models.DateField(blank=True)),
                ('出生地', models.CharField(blank=True, max_length=10)),
                ('所属事务所', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name_plural': '艺人',
                'db_table': '艺人',
            },
        ),
        migrations.CreateModel(
            name='个人图片',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('名字', models.CharField(max_length=10)),
                ('图片', models.ImageField(upload_to='image/')),
                ('关联', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.艺人')),
            ],
            options={
                'verbose_name_plural': '个人图片',
                'db_table': '个人图片',
            },
        ),
    ]
